/**
 * Downloads the JetBrains Mono + IBM Plex Mono weights used by the UI from
 * Google Fonts and self-hosts them under public/fonts, then generates
 * src/app/fonts.css with local @font-face rules. Keeps the app fully offline.
 *
 * Run from the project root:  node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const ROOT = process.cwd();
const FONT_DIR = path.join(ROOT, "public/fonts");
const OUT_CSS = path.join(ROOT, "src/app/fonts.css");

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,400;0,500;0,700;0,800;1,400&family=IBM+Plex+Mono:ital,wght@0,400;0,500;0,600;1,400&display=swap";

// A modern UA makes Google serve woff2.
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const KEEP_SUBSETS = new Set(["latin", "latin-ext"]);

await mkdir(FONT_DIR, { recursive: true });
const css = await (await fetch(CSS_URL, { headers: { "User-Agent": UA } })).text();

const blockRe = /\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[\s\S]*?\})/g;
const out = [];
let count = 0;
let m;
while ((m = blockRe.exec(css)) !== null) {
  const subset = m[1];
  let block = m[2];
  if (!KEEP_SUBSETS.has(subset)) continue;

  const fam = /font-family:\s*'([^']+)'/.exec(block)[1];
  const weight = /font-weight:\s*(\d+)/.exec(block)[1];
  const style = /font-style:\s*(\w+)/.exec(block)[1];
  const woffUrl = /src:\s*url\(([^)]+)\)/.exec(block)[1];

  const fileName =
    fam.toLowerCase().replace(/\s+/g, "-") +
    `-${weight}${style === "italic" ? "-italic" : ""}-${subset}.woff2`;

  const buf = Buffer.from(await (await fetch(woffUrl)).arrayBuffer());
  await writeFile(path.join(FONT_DIR, fileName), buf);
  count++;

  block = block.replace(
    /src:\s*url\([^)]+\)\s*format\([^)]+\)/,
    `src: url('/fonts/${fileName}') format('woff2')`,
  );
  out.push(block.trim());
}

const header = `/* Self-hosted fonts (latin + latin-ext) — generated by scripts/fetch-fonts.mjs. */\n`;
await writeFile(OUT_CSS, header + out.join("\n\n") + "\n");
console.log(`downloaded ${count} woff2 -> public/fonts/, wrote src/app/fonts.css`);
